export const emuResult = {
    "data":
    {
        "city_name": "Ankara",
        "lon": "32.85427",
        "timezone": "Europe/Istanbul",
        "lat": "39.91987",
        "country_code": "TR",
        "state_code": "68",
        "data": [
            {
                "moonrise_ts": 1663091129,
                "wind_cdir": "B",
                "rh": 55,
                "pres": 905,
                "high_temp": 22.8,
                "sunset_ts": 1663084862,
                "ozone": 307.3,
                "moon_phase": 0.826016,
                "wind_gust_spd": 4.7,
                "clouds": 0,
                "ts": 1663016460,
                "sunrise_ts": 1663039713,
                "app_min_temp": 12.2,
                "wind_spd": 2,
                "pop": 0,
                "wind_cdir_full": "batı",
                "moon_phase_lunation": 0.6,
                "slp": 1009.3,
                "high_temp_bc": 21.6,
                "app_max_temp": 21.8,
                "valid_date": "2022-09-13",
                "vis": 24.128,
                "snow": 0,
                "dewpt": 7.1,
                "low_temp_bc": 0,
                "uv": 7.1,
                "weather": {
                    "icon": "c01d",
                    "code": 800,
                    "description": "Açık gökyüzü"
                },
                "wind_dir": 262,
                "clouds_hi": 0,
                "precip": 0,
                "low_temp": 9.2,
                "max_temp": 22.8,
                "moonset_ts": 1663054909,
                "datetime": "2022-09-13",
                "temp": 17.1,
                "min_temp": 12.2,
                "clouds_mid": 5,
                "clouds_low": 4
            },
            {
                "moonrise_ts": 1663179128,
                "wind_cdir": "GB",
                "rh": 50,
                "pres": 910,
                "high_temp": 22.4,
                "sunset_ts": 1663171163,
                "ozone": 308.2,
                "moon_phase": 0.738329,
                "wind_gust_spd": 3,
                "clouds": 0,
                "ts": 1663102860,
                "sunrise_ts": 1663126170,
                "app_min_temp": 9.2,
                "wind_spd": 1.2,
                "pop": 0,
                "wind_cdir_full": "güneybatı",
                "moon_phase_lunation": 0.63,
                "slp": 1015.1,
                "high_temp_bc": 0,
                "app_max_temp": 21.3,
                "valid_date": "2022-09-14",
                "vis": 24.128,
                "snow": 0,
                "dewpt": 4.2,
                "low_temp_bc": 0,
                "uv": 7,
                "weather": {
                    "icon": "c01d",
                    "code": 800,
                    "description": "Açık gökyüzü"
                },
                "wind_dir": 221,
                "clouds_hi": 0,
                "precip": 0,
                "low_temp": 9.2,
                "max_temp": 22.4,
                "moonset_ts": 1663145279,
                "datetime": "2022-09-14",
                "temp": 16.1,
                "min_temp": 9.2,
                "clouds_mid": 0,
                "clouds_low": 0
            },
            {
                "moonrise_ts": 1663267325,
                "wind_cdir": "G",
                "rh": 40,
                "pres": 911.3,
                "high_temp": 26.2,
                "sunset_ts": 1663257464,
                "ozone": 295.9,
                "moon_phase": 0.642948,
                "wind_gust_spd": 3.7,
                "clouds": 0,
                "ts": 1663189260,
                "sunrise_ts": 1663212626,
                "app_min_temp": 9.2,
                "wind_spd": 1.5,
                "pop": 0,
                "wind_cdir_full": "güney",
                "moon_phase_lunation": 0.66,
                "slp": 1016.2,
                "high_temp_bc": 0,
                "app_max_temp": 25.3,
                "valid_date": "2022-09-15",
                "vis": 24.128,
                "snow": 0,
                "dewpt": 2.5,
                "low_temp_bc": 0,
                "uv": 7,
                "weather": {
                    "icon": "c01d",
                    "code": 800,
                    "description": "Açık gökyüzü"
                },
                "wind_dir": 176,
                "clouds_hi": 0,
                "precip": 0,
                "low_temp": 13.7,
                "max_temp": 26.2,
                "moonset_ts": 1663235552,
                "datetime": "2022-09-15",
                "temp": 17.8,
                "min_temp": 9.2,
                "clouds_mid": 0,
                "clouds_low": 0
            },
            {
                "moonrise_ts": 1663355808,
                "wind_cdir": "GGB",
                "rh": 27,
                "pres": 905.7,
                "high_temp": 31,
                "sunset_ts": 1663343764,
                "ozone": 286.9,
                "moon_phase": 0.544144,
                "wind_gust_spd": 1.6,
                "clouds": 0,
                "ts": 1663275660,
                "sunrise_ts": 1663299083,
                "app_min_temp": 13.7,
                "wind_spd": 1.4,
                "pop": 0,
                "wind_cdir_full": "güney-güneyWest",
                "moon_phase_lunation": 0.7,
                "slp": 1012.1,
                "high_temp_bc": 0,
                "app_max_temp": 28.9,
                "valid_date": "2022-09-16",
                "vis": 24.128,
                "snow": 0,
                "dewpt": 1.7,
                "low_temp_bc": 0,
                "uv": 6.9,
                "weather": {
                    "icon": "c01d",
                    "code": 800,
                    "description": "Açık gökyüzü"
                },
                "wind_dir": 194,
                "clouds_hi": 3,
                "precip": 0,
                "low_temp": 18.1,
                "max_temp": 31,
                "moonset_ts": 1663325648,
                "datetime": "2022-09-16",
                "temp": 22.7,
                "min_temp": 13.7,
                "clouds_mid": 0,
                "clouds_low": 0
            },
            {
                "moonrise_ts": 1663444650,
                "wind_cdir": "G",
                "rh": 29,
                "pres": 902,
                "high_temp": 32.8,
                "sunset_ts": 1663430065,
                "ozone": 282.6,
                "moon_phase": 0.445481,
                "wind_gust_spd": 1.9,
                "clouds": 0,
                "ts": 1663362060,
                "sunrise_ts": 1663385539,
                "app_min_temp": 17.4,
                "wind_spd": 1.7,
                "pop": 0,
                "wind_cdir_full": "güney",
                "moon_phase_lunation": 0.73,
                "slp": 1007.9,
                "high_temp_bc": 0,
                "app_max_temp": 30.5,
                "valid_date": "2022-09-17",
                "vis": 24.128,
                "snow": 0,
                "dewpt": 4.9,
                "low_temp_bc": 0,
                "uv": 6.8,
                "weather": {
                    "icon": "c01d",
                    "code": 800,
                    "description": "Açık gökyüzü"
                },
                "wind_dir": 177,
                "clouds_hi": 1,
                "precip": 0,
                "low_temp": 20.1,
                "max_temp": 32.8,
                "moonset_ts": 1663415458,
                "datetime": "2022-09-17",
                "temp": 25.5,
                "min_temp": 18.1,
                "clouds_mid": 0,
                "clouds_low": 0
            },
            {
                "moonrise_ts": 1663533893,
                "wind_cdir": "GD",
                "rh": 23,
                "pres": 899.4,
                "high_temp": 34.7,
                "sunset_ts": 1663516365,
                "ozone": 277.9,
                "moon_phase": 0.349992,
                "wind_gust_spd": 3.8,
                "clouds": 8,
                "ts": 1663448460,
                "sunrise_ts": 1663471996,
                "app_min_temp": 19.4,
                "wind_spd": 3.2,
                "pop": 0,
                "wind_cdir_full": "güneydoğu",
                "moon_phase_lunation": 0.77,
                "slp": 1005.1,
                "high_temp_bc": 0,
                "app_max_temp": 31.8,
                "valid_date": "2022-09-18",
                "vis": 24.128,
                "snow": 0,
                "dewpt": 2.4,
                "low_temp_bc": 0,
                "uv": 7,
                "weather": {
                    "icon": "c02d",
                    "code": 801,
                    "description": "Az bulutlu"
                },
                "wind_dir": 145,
                "clouds_hi": 15,
                "precip": 0,
                "low_temp": 16.9,
                "max_temp": 34.7,
                "moonset_ts": 1663504888,
                "datetime": "2022-09-18",
                "temp": 26.8,
                "min_temp": 19.9,
                "clouds_mid": 8,
                "clouds_low": 0
            },
            {
                "moonrise_ts": 1663537119,
                "wind_cdir": "B",
                "rh": 35,
                "pres": 901.2,
                "high_temp": 29.9,
                "sunset_ts": 1663602666,
                "ozone": 289.3,
                "moon_phase": 0.260448,
                "wind_gust_spd": 2.9,
                "clouds": 1,
                "ts": 1663534860,
                "sunrise_ts": 1663558453,
                "app_min_temp": 16.9,
                "wind_spd": 2.3,
                "pop": 0,
                "wind_cdir_full": "batı",
                "moon_phase_lunation": 0.8,
                "slp": 1007.7,
                "high_temp_bc": 0,
                "app_max_temp": 28.2,
                "valid_date": "2022-09-19",
                "vis": 24.128,
                "snow": 0,
                "dewpt": 6.5,
                "low_temp_bc": 0,
                "uv": 6.9,
                "weather": {
                    "icon": "c01d",
                    "code": 800,
                    "description": "Açık gökyüzü"
                },
                "wind_dir": 266,
                "clouds_hi": 1,
                "precip": 0,
                "low_temp": 16.1,
                "max_temp": 29.9,
                "moonset_ts": 1663593898,
                "datetime": "2022-09-19",
                "temp": 23.1,
                "min_temp": 16.6,
                "clouds_mid": 1,
                "clouds_low": 0
            }
        ]
    }
}